# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspen_api', '0002_auto_20221110_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='design_lead',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='team',
            name='mission_statement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='tech_lead',
            field=models.CharField(default='', max_length=60),
        ),
    ]
