# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspen_api', '0003_auto_20221111_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='url',
        ),
        migrations.AddField(
            model_name='team',
            name='product_lead',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='team',
            name='updates',
            field=models.TextField(default=''),
        ),
    ]
