# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspen_api', '0004_auto_20221111_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='repositories_owned',
            field=models.TextField(default=''),
        ),
    ]
